version: '3.9'


services:
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'

    environment:
      - MYSQL_ROOT_PASSWORD=K56a33--m1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=db.vinmartech

    volumes:
      - ./data/db:/var/lib/mysql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - MYSQL_ROOT_PASSWORD=K56a33--m1
      - MYSQL_DATABASE=db.vinmartech

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
