version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    restart: unless-stopped
    environment:
       MYSQL_DATABASE: 'vinmartech'
       MYSQL_ROOT_PASSWORD: 'K56a33--m1'
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    image: vinmartech-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: vinmartech-backend:latest 
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile  
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local

