version: '3.9'


services:
  db:
    image: mysql:8.0
    ports:
      - 8080:8080
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=K56a33--m1

    volumes:
      - ./data/db:/var/lib/mysql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    environment:
       - MYSQL_ROOT_PASSWORD=K56a33--m1

    ports:
      - 8000:8000

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
